# Generated by Django 5.1.3 on 2024-11-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_jobseeker_description_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('projectName', models.CharField(max_length=1000, null=True)),
                ('startFrom', models.DateTimeField(null=True)),
                ('endTo', models.DateTimeField(null=True)),
                ('clientName', models.CharField(max_length=1000, null=True)),
                ('Designation', models.CharField(max_length=100, null=True)),
                ('jobSeekerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Experiences', to='myApp.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='KeySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('jobSeekerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KeySkills', to='myApp.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('expeienceId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectDescriptions', to='myApp.experience')),
            ],
        ),
    ]
